filebeat.inputs:
  - type: log
    paths:
      - ../libs/common/src/logger/logs/*.log

output.logstash:
  hosts: ["logstash:5044"]

# Disable ILM and Ingest Pipeline since Logstash is used
setup.ilm.enabled: false
setup.template.enabled: false